- src/main/java/com/sudo/railo/ticket/domain/Qr.java
- src/main/java/com/sudo/railo/ticket/domain/Reservation.java
- src/main/java/com/sudo/railo/ticket/domain/ReservationStatus.java
- src/main/java/com/sudo/railo/ticket/domain/SeasonTicket.java
- src/main/java/com/sudo/railo/ticket/domain/SeasonTicketStatus.java
- src/main/java/com/sudo/railo/ticket/domain/Ticket.java
- src/main/java/com/sudo/railo/ticket/domain/TripType.java
- close #1 
- QR 엔티티 수정
- 예매 엔티티 추가
- 승차권 엔티티 수정
- 정기권 엔티티 수정
기존 @Jimin730 님이 작성해주신 엔티티를 ERD 설계에 맞게 수정하고, 예매 엔티티를 추가했습니다.  
일부 구현되지 않은 도메인에 대한 외래키는 `TODO` 로 남겨놓았으며,  
ERD 타입과 nullable 중심으로 리뷰해주시면 좋을것같습니다. 😁
정상적으로 추가되는것을 확인했습니다.
> [FEATURE] 승차권 관련 Entity 설계 및 생성

- build.gradle
- src/main/java/com/sudo/railo/global/config/SwaggerConfig.java
- close #23
- springdoc-openapi 의존성 추가
- Swagger OpenAPI 3.0 설정 추가
- JWT Bearer 토큰 인증 스키마 구성
- 도메인 별 엔드포인트 분류 및 API 태그 그룹 정의 (인증, 회원, 승차권, 예매, 결제 등)
현재 태그 이름, 설명, 서버 URL은 임시로 설정된 상태입니다.
각자 담당하신 도메인 개발 시 필요에 따라 자유롭게 수정해 주시면 될 것 같습니다. :)
- Swagger URL : http://localhost:8080/swagger-ui/index.html
- JWT 토큰 입력 시 `Bearer` 제외하고 토큰만 입력
- 서버 설정: 로컬/개발/운영 서버
> [FEATURE] Swagger 설정 #23

- src/main/java/com/sudo/railo/global/exception/ErrorTestController.java
- src/main/java/com/sudo/railo/global/exception/GlobalExceptionHandler.java
- src/main/java/com/sudo/railo/global/exception/TestRequestDTO.java
- src/main/java/com/sudo/railo/global/exception/error/BusinessException.java
- src/main/java/com/sudo/railo/global/exception/error/ErrorCode.java
- src/main/java/com/sudo/railo/global/exception/error/ErrorResponse.java
- src/main/java/com/sudo/railo/global/exception/error/GlobalError.java
- src/main/java/com/sudo/railo/member/exception/MemberError.java
- close #13
- 글로벌 예외 처리 시스템 구축
- GlobalExceptionHandler 추가로 통합 예외 처리
- BusinessException 및 커스텀 에러 코드 시스템 구현
- ErrorResponse 표준 응답 형식 정의
- 도메인별 에러 코드 정의
- GlobalError, MemberError 예시 num 추가
- 각 도메인별 에러 코드 관리
- 개발용 테스트 API 추가 (팀원들 테스트 이후 삭제 예정)
- 에러 처리 테스트용 컨트롤러
- Validation, 인증, 비즈니스 로직 에러 테스트 엔드포인트
예외들을 전역적으로 처리하기 위한 통합 예외 처리를 구현했습니다. 
도메인 별 에러 코드 체계와 응답 형식 표준화에 중점으로 리뷰해주시면 좋을 것 같습니다.
ErrorTestController을 통한 에러 응답 API 테스트를 HoppScotch의 `Test` 폴더에 등록해두었으니 한번 확인해보시면 될 것 같습니다 :)
모든 에러 케이스에 대해 정상적으로 응답되는 것을 확인했습니다.
1. `@RequestBody` 누락
2. `@RequestBody` Validation 실패
3. `@RequestParam` 누락
4. `@RequestParam` Validation 실패
5. `@PathVariable` Validation 실패
6. GlobalError 테스트
7. MemberError 테스트
8. 일반 예외 (Server Error 500)
> [FEATURE] 글로벌 예외 처리 구현

- src/main/java/com/sudo/railo/global/domain/BaseEntity.java
- close #22 
- BaseEntity 클래스 정의 (`createdAt`, `updatedAt`)
- `BaseEntity`를 상속받아 `createdAt`과 `updatedAt` 필드를 관리하시면 됩니다.
- 없음
> [FEATURE] BaseEntity 구현

- .editorconfig
- close #51
- `.editorconfig` 추가
다양한 에디터에서 핵데이 컨벤션을 적용하기 위해 `.editorconfig`를 추가합니다.
확인하신 후 별도의 코멘트 없이 Approve 해주시면 감사하겠습니다.
(main 브랜치에 force-push 가능하나, 변경사항 공유 위해 별도 PR을 작성했습니다)
> [CHORE] .editorconfig 추가

- src/main/java/com/sudo/railo/booking/application/FareCalculationService.java
- src/main/java/com/sudo/railo/booking/application/ReservationApplicationService.java
- src/main/java/com/sudo/railo/booking/application/ReservationScheduler.java
- src/main/java/com/sudo/railo/booking/application/ReservationService.java
- src/main/java/com/sudo/railo/booking/application/SeatReservationService.java
- src/main/java/com/sudo/railo/booking/application/dto/request/FareCalculateRequest.java
- src/main/java/com/sudo/railo/booking/application/dto/request/ReservationCreateRequest.java
- src/main/java/com/sudo/railo/booking/application/dto/request/ReservationDeleteRequest.java
- src/main/java/com/sudo/railo/booking/application/dto/response/ReservationCreateResponse.java
- src/main/java/com/sudo/railo/booking/config/BookingConfig.java
- src/main/java/com/sudo/railo/booking/domain/PassengerSummary.java
- src/main/java/com/sudo/railo/booking/domain/Reservation.java
- src/main/java/com/sudo/railo/booking/domain/SeatReservation.java
- src/main/java/com/sudo/railo/booking/exception/BookingError.java
- src/main/java/com/sudo/railo/booking/infra/ReservationRepository.java
- src/main/java/com/sudo/railo/booking/infra/SeatReservationRepository.java
- src/main/java/com/sudo/railo/booking/presentation/BookingController.java
- src/main/java/com/sudo/railo/booking/presentation/ReservationController.java
- src/main/java/com/sudo/railo/booking/presentation/SeatReservationController.java
- src/main/java/com/sudo/railo/booking/success/FareSuccess.java
- src/main/java/com/sudo/railo/booking/success/ReservationSuccess.java
- src/main/java/com/sudo/railo/train/infrastructure/SeatRepository.java
- close #2 
- 예약 및 운임 계산 서비스, 컨트롤러 추가
- 예약 관련 엔티티 수정, DTO 생성
- 예약, 좌석 관련 레포지토리 추가
- 에러 및 성공 응답 추가
- 기존 코드 개선
- 좌석 엔티티를 가져와야해서 좌석 도메인 레포지토리를 추가했습니다.
- 좌석 예약 현황 엔티티의 경우 '예약 ID'를 필수로 받고있기 때문에  
미리 스케줄과 열차별로 예약 현황 레코드가 삽입되어있는것이 아닌,  
예약이 생성될때마다 좌석 예약 현황이 생성되는것으로 판단했습니다.
- 따라서 기존 엔티티를 변경하는식인 `SeatReservation`의 일부 메서드를 deprecate처리했습니다.
- `ReservationService`의 `createReservation`에서 사용되는 각 도메인 별 예외를  
기본 `Exception`으로 대체해놓은 상태입니다.  
추후 각 도메인 별 에러코드가 작성 및 구현됐을 때 반영하겠습니다.
- 예약 시 `Reservation` 엔티티와 `SeatReservation` 엔티티 모두 생성합니다.
- `/booking/fare` (POST): 운임 계산
- `/booking/reservation` (POST): 예약 생성
- `/booking/reservation` (DELETE): 예약 삭제
없음
> [FEATURE] 예매 로직 구현

- src/main/java/com/sudo/railo/train/application/TrainScheduleService.java
- src/main/java/com/sudo/railo/train/application/dto/response/TrainSearchResponse.java
- close #68
- TrainSearchResponse에 trainScheduleId 필드 추가
- TrainScheduleService.createTrainSearchResponse() 메소드에서 trainScheduleId 전달하도록 수정
열차 선택 후 상세 조회를 위한 Id식별자를 알 수 없어 열차 조회에 `trainScheduleId` 를 포함하도록 수정했습니다.
없음
> feat: 열차 조회 응답에 trainScheduleId 추가 (#68)

- build.gradle
- src/main/java/com/sudo/railo/global/security/SecurityConfig.java
- close #77 
- `spring-boot-starter-actuator` 의존성 추가
- `micrometer-registry-prometheus` 의존성 추가
- 자세한 내용은 회의 시간에 공유하겠습니다!
- 모니터링 환경 구축을 위해 `docker`, `docker-compose`가 필요합니다.
- `application.yml`에 다음과 같은 정보가 필요합니다.
```yml
management:
endpoints:
web:
exposure:
include: prometheus, health, info
endpoint:
health:
show-details: always
```
> [CHORE] Prometheus 모니터링 연동

- .github/workflows/deploy_raillo_with_k8s.yml
- .github/workflows/gradle_build_and_test.yml
- close #86
이미지 빌드에 실패하는 상황을 방지하기 위해 해당 워크플로우를 추가했습니다.
- gradle_build_and_test.yml 작성
- Java 17 및 Gradle 설정
- ./gradlew build, ./gradlew test 자동 실행
- deploy_raillo_with_k8s.yml 작성
- Docker 이미지 빌드 및 ECR 푸시
- EKS 클러스터에서 raillo-backend deployment rolling restart
- Secrets 설정 (DB_URL, DB_USERNAME, DB_PASSWORD 등)을 GitHub Secrets에 `dev` Environment에 등록했습니다.
- `dev` 브랜치의 테스트는 운영 DB에 영향을 끼치지 않도록 `raillo-test` 스키마를 만들어 사용하도록 했습니다.
테스트 결과는 Actions 탭에서 확인 가능하며, JUnit 리포트가 자동 업로드됩니다.
> [CHORE] Github Action CI/CD 스크립트 작성

- src/main/resources/application-prod.yml
- close #0
- cors 오리진 도메인 오타가 있어 com -> shop으로 수정했습니다.
없음
없음
> fix: cors 오리진 도메인 오타 수정

- .github/workflows/gradle_build_and_test.yml
- close #86
- 트리거되는 브랜치 네이밍에 오류가 있어 수정했습니다. (`dev` -> `develop`)
없음
없음
> [CI] 트리거 브랜치 네이밍 오류 수정

- src/main/resources/application-prod.yml
- close #103
- application-prod.yml 에 actuator 설정 추가
없음
없음
> [CHORE] Prometheus 메트릭 수집을 위한 엔드포인트 활성화 설정 추가

- src/main/java/com/sudo/railo/global/security/jwt/JwtFilter.java
- src/main/java/com/sudo/railo/global/security/jwt/TokenProvider.java
- close #108 
- `TokenProvider`, `JwtFilter` 파일 수정
비밀번호 찾기 시 발급 되는 임시 토큰이 비밀번호 변경 페이지에 접근할 수 있도록 접근 권한 부분 코드를 수정하였습니다.
임시 토큰으로 비밀번호 변경 엔드포인트에 접근 가능한 것 확인하였고, 
기본 accessToken 으로도 접근 가능한 것을 테스트로 확인하였습니다 👍 
없음
> [FEATURE] 임시토큰 접근 권한 수정

- src/main/java/com/sudo/railo/booking/application/QrService.java
- src/main/java/com/sudo/railo/booking/application/ReservationApplicationService.java
- src/main/java/com/sudo/railo/booking/application/TicketService.java
- src/main/java/com/sudo/railo/booking/docs/TicketControllerDocs.java
- src/main/java/com/sudo/railo/booking/domain/Qr.java
- src/main/java/com/sudo/railo/booking/domain/Ticket.java
- src/main/java/com/sudo/railo/booking/exception/BookingError.java
- src/main/java/com/sudo/railo/booking/infra/QrRepository.java
- src/main/java/com/sudo/railo/booking/infra/TicketRepository.java
- src/main/java/com/sudo/railo/booking/presentation/ReservationController.java
- src/main/java/com/sudo/railo/booking/presentation/TicketController.java
- src/main/java/com/sudo/railo/booking/success/TicketSuccess.java
- close #97 
- QR 레포지토리 및 서비스 구현
- Ticket 레포지토리 및 서비스 구현
- Ticket 생성 로직, 컨트롤러(조회) 추가
범진님이 구현해주신 결제 관련 로직을 참고하여 결제 완료 시 Ticket 엔티티를 추가하는 방식(기존)에서
이미 생성되어있는 Ticket 엔티티의 필드를 수정하는 로직을 위해 예약 생성 시 Ticket 엔티티를 추가하는 방식으로 변경했습니다.
이로 인해 기존 `ReservationAllocationService`의 이름을 다시 `ReservationApplicationService`로 변경했습니다.
(예약 흐름에서 좌석할당만 있던것이 승차권 생성까지 포함되어버렸기 때문입니다.)
Ticket 조회의 경우, 인증된 유저만 접근 가능하며 자신이 예약또는 발급한 Ticket만 조회되도록 했습니다.
없음
> [FEATURE] 티켓, QR 생성 및 조회 로직 구현

- src/main/java/com/sudo/railo/booking/application/ReservationApplicationService.java
- src/main/java/com/sudo/railo/booking/application/TicketService.java
- src/main/java/com/sudo/railo/booking/domain/Ticket.java
- close #107
- 승차권(Ticket) 엔티티에 좌석 예약 현황(SeatReservation) 관계 추가 (일대일)
- #97 에서 분기한 브랜치입니다.
- `/booking/domain/Ticket.java` 파일만 확인하시면 됩니다.
- 승차권 조회로직은 변경되지 않았습니다, 승차권 조회 시 무슨 항목이 필요한지 논의 후
TicketDetail Record 객체를 생성하여 추가 커밋 올리겠습니다.
없음
> [FEATURE] 승차권 - 좌석 예약 현황 관계 추가 및 승차권 조회 로직 수정

- src/main/java/com/sudo/railo/train/application/StationFareCreator.java
- src/main/java/com/sudo/railo/train/application/StationService.java
- src/main/java/com/sudo/railo/train/application/TrainScheduleCreator.java
- src/main/java/com/sudo/railo/train/application/TrainScheduleTemplateService.java
- src/main/resources/application-prod.yml
- close #118
- `application.yml`에 `management.metrics.distribution.percentiles-histogram` 설정 추가
- `http.server.requests`에 대해 `status`, `method`, `uri` 라벨 조합의 시계열 강제 생성
없음
없음
> [CHORE] Prometheus – status 라벨 포함 및 5xx 에러율 분석 가능하게 설정

- src/main/java/com/sudo/railo/train/application/StationFareCreator.java
- src/main/java/com/sudo/railo/train/application/StationService.java
- src/main/java/com/sudo/railo/train/application/TrainScheduleCreator.java
- src/main/java/com/sudo/railo/train/application/TrainScheduleTemplateService.java
This reverts commit 6d798b527f7ec4b44262e73dbb3c3446fa185736.
- close #124 
- `6d798b52` 커밋 Revert
없음
없음
> [CHORE] #116 이슈 Revert 작업

- src/main/java/com/sudo/railo/booking/domain/Ticket.java
- close #132 
- Ticket 엔티티 `reservation`, `seatReservation` `@OnDelete` 속성 추가
없음
없음
> [FIX] Ticket 삭제 오류

- src/main/java/com/sudo/railo/train/application/dto/response/TrainSearchResponse.java
- src/main/java/com/sudo/railo/train/infrastructure/SeatRepositoryCustomImpl.java
- close #141
- 좌석 상세 조회에서 예약 구간 겹침 조건을 상/하행에 따라 분기 처리하여 정확하게 예약 상태 판단
- TrainSearchResponse 내부에서 travelTime이 음수일 경우 24시간을 더해 보정
없음
없음
> [BUG] 자정을 넘는 열차 소요 시간 계산 오류, 상행 좌석 선택 오류

- src/main/java/com/sudo/railo/booking/application/TicketService.java
- src/main/java/com/sudo/railo/booking/application/dto/response/TicketReadResponse.java
- src/main/java/com/sudo/railo/booking/docs/TicketControllerDocs.java
- src/main/java/com/sudo/railo/booking/infra/TicketRepositoryCustom.java
- src/main/java/com/sudo/railo/booking/infra/TicketRepositoryCustomImpl.java
- src/main/java/com/sudo/railo/booking/presentation/TicketController.java
- src/main/java/com/sudo/railo/booking/success/TicketSuccess.java
- close #144 
- 승차권 조회 시 반환타입 추가
- 승차권 조회 성공 시 문구 오타 수정
성능 최적화가 필요해보입니다. 😢
없음
> [FIX] 승차권 조회 시 과다 정보 노출 및 중첩

- src/main/java/com/sudo/railo/booking/infra/ReservationRepositoryCustomImpl.java
- src/main/java/com/sudo/railo/booking/infra/TicketRepositoryCustomImpl.java
- close #147 
- `TrainSchedule`이 아닌 `ScheduleStop`에서 시간을 가져오도록 수정
없음
없음
> [FIX] 승차권, 예약 조회 시 잘못된 시간을 가져오는 이슈

- src/main/java/com/sudo/railo/auth/docs/AuthControllerDocs.java
- src/main/java/com/sudo/railo/auth/presentation/AuthController.java
- src/main/java/com/sudo/railo/auth/util/CookieManager.java
- close #183 
- AuthController에 removeRefreshTokenCookie() 메서드 추가
- 기존 refreshToken이 담겨있는 cookie를 무효화
- CookieManager 클래스를 만들어 cookie 관련 메서드를 분리해서 관리
Cookie에 담겨있는 refreshToken 정보가 무효화 된 것을 확인할 수 있습니다 !
없음
> [FEATURE] 로그아웃 시 Cookie에 담긴 refreshToken 만료 로직 추가

- src/main/java/com/sudo/railo/train/application/TrainScheduleService.java
- src/main/java/com/sudo/railo/train/application/TrainSearchApplicationService.java
- src/main/java/com/sudo/railo/train/application/TrainSearchService.java
- src/main/java/com/sudo/railo/train/application/dto/SectionSeatStatus.java
- src/main/java/com/sudo/railo/train/application/dto/projection/ReservationInfoProjection.java
- src/main/java/com/sudo/railo/train/application/dto/projection/TrainSeatInfoBatch.java
- src/main/java/com/sudo/railo/train/application/dto/projection/TrainSeatInfoProjection.java
- src/main/java/com/sudo/railo/train/application/dto/response/SeatTypeInfo.java
- src/main/java/com/sudo/railo/train/application/dto/response/StandingTypeInfo.java
- src/main/java/com/sudo/railo/train/domain/type/SeatAvailabilityStatus.java
- src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepositoryCustom.java
- src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepositoryCustomImpl.java
- src/main/java/com/sudo/railo/train/presentation/TrainSearchController.java
- close #197 
- 기존: 객차별 좌석 수 + 전체 좌석 수를 별도 쿼리로 조회
- 개선: 1개 쿼리에서 객차별 좌석 수 조회 후 메모리에서 전체 좌석 수 계산
- 예상 효과: DB 왕복 횟수 감소로 응답 시간 단축
- StandingCalculationResult record 삭제하여 불필요한 중간 객체 제거
- 입석 계산 로직을 SectionSeatStatus로 통합하여 단일 책임 원칙 적용
- 예약 가능 여부 판단을 Service Layer에서 한 번만 수행하도록 중복 제거
- available → remaining: "남은 좌석"이라는 의미 명확화
- occupied → reserved: 예약 시스템 컨텍스트에 맞는 용어 사용
- maxAdditionalStanding → remainingStanding: 직관적인 변수명으로 변경
- 모든 입석 계산을 standingRatio(0.15) 비율 기반으로 통일 (열차 전체 좌석수의 15%)
예약 정보 조회도 통합을 시도했으나 (좌석 예약, 입석 예약) 기존 분리 구조를 그대로 가져가기로 결정했습니다.
- 좌석 예약과 입석 예약 통합 시 복잡한 LEFT JOIN 추가로 인한 성능 리스크
- 메모리 사용량 증가 및 애플리케이션 레이어에서의 추가 연산 부담
없음
> [REFACTOR] 열차 조회 로직 개선

- src/main/java/com/sudo/railo/booking/application/dto/response/TicketReadResponse.java
- close #236 
- `TicketReadResponse` `seatReservationId` 삭제
이전 PR에 같이 포함시킬걸 그랬네요, 죄송합니다 😢
없음
> [BUG] Ticket 도메인 getMyTickets 관련 조회 오류 수정

- src/test/java/com/sudo/railo/booking/application/FareCalculationServiceTest.java
- close #216 
- 운임 계산 테스트 코드 작성
없음
없음
> [TEST] 운임 계산 서비스 테스트
