goorm-sudo/raillo-backend

src/main/java/com/sudo/railo/ticket/domain/Ticket.java
- close #28
- 승차권 엔티티의 승차권 번호 관련 필드 이름을 수정하였습니다.
- `wctNumber` -> `vendorCode` (발행 주체 코드)
- `saleAt` -> `purchaseDate`  
(발매 일자, 발매는 결제 시점과 동일하게 이루어집니다. `purchase`를 사용했습니다.)  
(그리고 'MMdd' 형식의 '일자'이기 때문에 `Date`를 사용했습니다.)
- `saleSeqNumber` -> `purchaseSeq` (발매 순번, 'Sequence'를 사용했습니다.)
- `pwd` -> `purchaseUid` (발매 고유번호, 'Unique Identifier'를 사용했습니다.)
아직 해당 엔티티의 필드를 참조하는 코드가 없어서 필드 이름만 바꿔둔 상태입니다.
앞으로 변경된 필드 이름을 사용해주시면 감사하겠습니다!
=> refactor: 승차권 엔티티 승차권 번호 관련 필드 이름 변경 (#28)

src/main/java/com/sudo/railo/global/config/QueryDslConfig.java, src/main/java/com/sudo/railo/global/redis/MemberRedis.java, src/main/java/com/sudo/railo/global/redis/Redis.java, src/main/java/com/sudo/railo/global/redis/RedisConfig.java, src/main/java/com/sudo/railo/global/redis/RedisUtil.java, src/main/java/com/sudo/railo/global/security/SecurityConfig.java, src/main/java/com/sudo/railo/member/application/MemberAuthService.java, src/main/java/com/sudo/railo/member/application/MemberAuthServiceImpl.java, src/main/java/com/sudo/railo/member/application/MemberNoGenerator.java, src/main/java/com/sudo/railo/member/application/dto/request/SignUpRequest.java, src/main/java/com/sudo/railo/member/application/dto/response/SignUpResponse.java, src/main/java/com/sudo/railo/member/domain/Member.java, src/main/java/com/sudo/railo/member/domain/MemberDetail.java, src/main/java/com/sudo/railo/member/domain/SocialAccount.java, src/main/java/com/sudo/railo/member/infra/MemberRepository.java, src/main/java/com/sudo/railo/member/infra/MemberRepositoryCustom.java, src/main/java/com/sudo/railo/member/infra/MemberRepositoryCustomImpl.java, src/main/java/com/sudo/railo/member/presentation/AuthController.java, src/main/java/com/sudo/railo/member/success/AuthSuccess.java, src/main/java/com/sudo/railo/ticket/domain/Ticket.java
- close #16 
- redis 설정 파일 추가
- QueryDsl 설정 파일 추가 
- Member 엔티티 수정
- BaseEntity 적용
- MemberDetail 디폴트 값 적용
- `@Builder` 적용  
- 회원가입 로직 구현
- QueryDsl 을 적용하여 이메일로 회원 중복 확인
- record 타입 dto 사용
- 회원가입 로직 mvc 구현
- AuthSuccess Enum 파일 추가 
- 회원번호 발급 로직 구현
- 레디스를 이용하여 `현재 날짜 + 카운터` 조합으로 12자리 회원번호 발급
코레일 회원가입 시 중복된 회원을 확인하기 위해서 본인인증을 통해 확인을 하고있는데, 
우선 기본적인 회원가입 로직을 구현해 놓고 나중에 본인인증 로직을 구현하여 중복된 회원인지를 검증하는 로직을 추가해보려고 합니다!
현재는 회원 email 을 unique 로 두고 중복된 회원인지를 확인할 수 있도록 구현하였습니다.
코레일에서 회원가입 시 발급하는 회원 번호는 레디스를 사용하여 날짜와 카운터 방식을 조합하는 방식으로 구현하였습니다.
처음엔 `YYMMdd + 카운터` 방식으로 구현하여 총 10자리로 만들어 회원가입 시 1씩 증가할 수 있도록 구현하였는데, 
이렇게 되면 언젠간 중복되는 회원 번호가 나올 수 있을 것 같아서 `yyyyMMdd + 카운터` 방식의 총 12자리 회원번호가 만들어질 수 있도록 구현하였습니다.
회원가입을 테스트 해볼 수 있도록 HoppScotch의 Member 폴더에 테스트를 추가해 두었습니다.
ddd 패키지 구조를 적용해보았는데 이런 방식으로 적용하는 건지 정확하게 알지 …
=> [FEATURE] 기본 회원가입 기능 구현

build.gradle, src/main/java/com/sudo/railo/global/config/CorsConfig.java, src/main/java/com/sudo/railo/global/exception/GlobalExceptionHandler.java, src/main/java/com/sudo/railo/global/redis/LogoutRedis.java, src/main/java/com/sudo/railo/global/redis/MemberRedis.java, src/main/java/com/sudo/railo/global/redis/RedisConfig.java, src/main/java/com/sudo/railo/global/redis/RedisError.java, src/main/java/com/sudo/railo/global/redis/RedisUtil.java, src/main/java/com/sudo/railo/global/security/CustomUserDetailsService.java, src/main/java/com/sudo/railo/global/security/SecurityConfig.java, src/main/java/com/sudo/railo/global/security/TokenError.java, src/main/java/com/sudo/railo/global/security/jwt/JwtAccessDeniedHandler.java, src/main/java/com/sudo/railo/global/security/jwt/JwtAuthenticationEntryPoint.java, src/main/java/com/sudo/railo/global/security/jwt/JwtFilter.java, src/main/java/com/sudo/railo/global/security/jwt/TokenProvider.java, src/main/java/com/sudo/railo/global/security/util/SecurityUtil.java, src/main/java/com/sudo/railo/member/application/MemberAuthService.java, src/main/java/com/sudo/railo/member/application/MemberAuthServiceImpl.java, src/main/java/com/sudo/railo/member/application/MemberNoGenerator.java, src/main/java/com/sudo/railo/member/application/dto/request/MemberNoLoginRequest.java, src/main/java/com/sudo/railo/member/application/dto/request/TokenRequest.java, src/main/java/com/sudo/railo/member/application/dto/response/TokenResponse.java, src/main/java/com/sudo/railo/member/presentation/AuthController.java, src/main/java/com/sudo/railo/member/success/AuthSuccess.java
- close #25
- Redis 관련 파일 코드 리팩토링
- `RedisConfig` 파일 수정 및 설정 추가
- `RedisUtil` 파일 내 메서드 추가
- `MemberRedis` 파일 코드 리팩토링
- Spring Security + JWT 로직 구현
- JWT 의존성 버전 문제로 0.11.2 로 다운그레이드
- `SecurityUtil` 추가
- `SecurityConfig` 파일 수정
- `CorsConfig` 설정 추가
- 로그인 로직 구현
- 로그아웃 로직 구현
이번 기능을 구현하면서 Redis 관련 파일들을 모두 리팩토링 하게 되었습니다.
- RedisConfig 에 `customStringRedisTemplate`,`customObjectRedisTemplate` 두 가지 방식으로 레디스에 저장할 수 있도록 설정 변경
- RedisUtil 에 로직 구현을 위한 메서드 추가 및 수정
- MemberRedis 코드 리팩토링
<br>
- 기존에 사용하던 JWT 버전 사용 시 오류 해결이 되지 않아 0.11.2 로 다운그레이드 하게 되었습니다.
- SecurityConfig 파일 수정을 통해 메인페이지와 `signup`, `login`, `swagger` 경로를 제외한 모든 경로는 인증이 필요할 수 있도록 수정하였습니다.
** 로직을 구현하시면서 테스트 시, 인증 부분을 잠시 제거하고 싶으신 분들은 `authorizeHttpRequests` 부분에 테스트를 원하는 요청 경로만 잠시 permit 해주시고 나중에 제거 해주시면 될 것 같습니다.
- SecurityUtil 파일을 추가하여 **로그인 …
=> [FEATURE] 회원번호 로그인 및 로그아웃 기능 구현

src/main/java/com/sudo/railo/global/security/SecurityConfig.java, src/main/java/com/sudo/railo/member/application/MemberService.java, src/main/java/com/sudo/railo/member/application/MemberServiceImpl.java, src/main/java/com/sudo/railo/member/application/dto/request/GuestRegisterRequest.java, src/main/java/com/sudo/railo/member/application/dto/response/GuestRegisterResponse.java, src/main/java/com/sudo/railo/member/domain/Member.java, src/main/java/com/sudo/railo/member/exception/MemberError.java, src/main/java/com/sudo/railo/member/infra/MemberRepository.java, src/main/java/com/sudo/railo/member/presentation/MemberController.java, src/main/java/com/sudo/railo/member/success/MemberSuccess.java
- close #39 
- SpringConfig 비회원 등록 요청 경로 추가
- 비회원 등록 로직 구현
비회원 정보 등록 시 요청으로 `name`, `phoneNumber`, `password` 3가지 정보를 받아옵니다.
서비스 로직에서 먼저 이 3가지 정보가 DB에 저장되어 있는지 확인하여 중복 검증을 수행하게 됩니다.
3가지 정보가 1가지라도 일치하지 않는다면 다른 비회원 정보로 보고 요청 정보가 저장되며,
3가지 정보가 모두 같다면 중복된 비회원 정보 예외를 던지게 됩니다.
테스트는 Hoppscotch 에 올려두었습니다 !
=> [FEATURE] 비회원 정보 저장 로직 구현

src/main/java/com/sudo/railo/global/domain/YesNo.java, src/main/java/com/sudo/railo/global/exception/error/GlobalError.java, src/main/java/com/sudo/railo/train/application/TrainScheduleService.java, src/main/java/com/sudo/railo/train/application/dto/request/OperationCalendarItem.java, src/main/java/com/sudo/railo/train/application/dto/request/ScheduleSearchRequest.java, src/main/java/com/sudo/railo/train/application/dto/response/TrainScheduleSuccess.java, src/main/java/com/sudo/railo/train/domain/TrainSchedule.java, src/main/java/com/sudo/railo/train/domain/status/OperationStatus.java, src/main/java/com/sudo/railo/train/domain/type/BusinessDayType.java, src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepository.java, src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepositoryCustom.java, src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepositoryCustomImpl.java, src/main/java/com/sudo/railo/train/presentation/TrainScheduleController.java
- close #37 
- 운행 캘린더 조회 API 구현 (`/api/v1/train-schedule/calendar`)
- 금일부터 한 달간의 열차 운행 여부를 조회
- 운행일/비운행일, 평일/주말/공휴일 여부 포함
- TrainScheduleRepository.findDatesWithActiveSchedules() 쿼리 작성
- 활성(ACTIVE, DELAYED) 상태의 스케줄만 조회
- 운행 스케줄 존재 여부와 휴일 판별을 위한 OperationCalendarItem DTO로 응답 정의
- 영업일 구분 Enum (`BusinessDayType`) 및 Y/N 변환 Enum (`YesNo`) 추가
아래 이미지의 캘린더 선택을 위한 조회 API입니다.
API 조회 결과는 아래와 같습니다.
- 현재 `isHoliday()`는 주말만 판단하고 있으며, 추후 2차로 넘어가서 시간이 남는다면 공휴일 API 연동 작업을 할 예정입니다. (TODO)
- 캘린더 response는 평일/주말/공휴일 구분과 예약 가능 여부를 포함합니다.
- JPA 쿼리 튜닝 및 캐싱 전략은 2차로 넘길 예정입니다. 
> 아직 현재 시간 이후, 선택한 시간 이후의 필터링은 적용하지 못했습니다. 열차 조회 (#5) 작업을 마친 후 다시 작업하여 올리겠습니다.
=> [FEATURE] 열차 운행 캘린더 조회

src/main/java/com/sudo/railo/global/security/TokenError.java, src/main/java/com/sudo/railo/global/security/jwt/JwtAccessDeniedHandler.java, src/main/java/com/sudo/railo/global/security/jwt/JwtAuthenticationEntryPoint.java, src/main/java/com/sudo/railo/global/security/jwt/TokenProvider.java, src/main/java/com/sudo/railo/member/application/MemberAuthService.java, src/main/java/com/sudo/railo/member/application/MemberAuthServiceImpl.java, src/main/java/com/sudo/railo/member/application/MemberService.java, src/main/java/com/sudo/railo/member/application/MemberServiceImpl.java, src/main/java/com/sudo/railo/member/application/dto/response/ReissueTokenResponse.java, src/main/java/com/sudo/railo/member/docs/AuthControllerDocs.java, src/main/java/com/sudo/railo/member/presentation/AuthController.java, src/main/java/com/sudo/railo/member/presentation/MemberController.java, src/main/java/com/sudo/railo/member/success/AuthSuccess.java
- close #42 
- AccessToken 재발급 로직 구현
- `TokenProvider` 에 reissue 메서드 수정
- 토큰 재발급 로직에 따라 `MemberAuthService`, `MemberAuthServiceImpl`, `AuthController` 파일에 코드 추가
- `TokenError` 및 `AuthSuccess` 코드 추가
- Swagger api 문서화를 위한 코드 추가
- AccessToken 재발급 로직 swagger 코드 추가
- MemberService, MemberServiceImpl, MemberController 코드 리팩토링
- Service 는 비즈니스 로직에 집중하고 Http 관련 작업은 controller 에서 처리할 수 있도록 코드 리팩토링
유저의 RefreshToken 유효시간은 만료 되지 않았지만, AccessToken 유효 시간이 만료 되어 클라이언트 측에 401 에러가 뜬 상황일 때 AccessToken 을 재발급 받을 수 있는 로직을 구현하였습니다.
토큰을 재발급 받는 로직은 다음과 같습니다.
1. 요청 헤더에 `refreshToken` 을 보내 `accessToken` 재발급 요청
2. 로그인된 사용자 정보로 redis 에 저장된 `refreshToken` 정보와 요청으로 넘어온 `refreshToken` 정보가 일치하는지 검증
3. 일치하면 `accessToken` 을 새로 만들어 발급
만약 refreshToken 또한 유효시간이 만료 되었다면 클라이언트 측으로 401 에러가 뜨게 됩니다.
이때, 클라이언트 측에서는 재로그인을 통해 …
=> [FEATURE] AccessToken 재발급 로직 구현

src/main/java/com/sudo/railo/global/redis/RedisUtil.java, src/main/java/com/sudo/railo/global/security/SecurityConfig.java, src/main/java/com/sudo/railo/global/security/TokenError.java, src/main/java/com/sudo/railo/global/security/jwt/JwtFilter.java, src/main/java/com/sudo/railo/global/security/jwt/TokenProvider.java, src/main/java/com/sudo/railo/member/application/MemberAuthService.java, src/main/java/com/sudo/railo/member/application/MemberAuthServiceImpl.java, src/main/java/com/sudo/railo/member/application/MemberService.java, src/main/java/com/sudo/railo/member/application/MemberServiceImpl.java, src/main/java/com/sudo/railo/member/application/dto/request/FindMemberNoRequest.java, src/main/java/com/sudo/railo/member/application/dto/request/FindPasswordRequest.java, src/main/java/com/sudo/railo/member/application/dto/response/TemporaryTokenResponse.java, src/main/java/com/sudo/railo/member/application/dto/response/VerifyMemberNoResponse.java, src/main/java/com/sudo/railo/member/docs/AuthControllerDocs.java, src/main/java/com/sudo/railo/member/exception/AuthError.java, src/main/java/com/sudo/railo/member/exception/MemberError.java, src/main/java/com/sudo/railo/member/infra/MemberRepositoryCustom.java, src/main/java/com/sudo/railo/member/infra/MemberRepositoryCustomImpl.java, src/main/java/com/sudo/railo/member/presentation/AuthController.java, src/main/java/com/sudo/railo/member/success/AuthSuccess.java
- close #17 
- 회원 번호 찾기 로직 구현
- 비밀 번호 찾기 로직 구현
- securityConfig 경로 추가
- 기존 이메일 검증 로직 반환 타입 변경
- 구현 기능 Swagger 문서화
현재 회원 번호 찾기 로직 흐름은 다음과 같습니다.
1. 회원의 `이름`, `휴대폰 번호`를 요청으로 받음
2. DB에 해당 정보를 가진 회원이 있는지 확인
3. 일치 하는 회원이 있다면 회원번호를 레디스에 잠시 저장 (유효시간 5분)
4. 찾아온 회원 정보에 있는 이메일로 이메일 인증 코드를 보내고, 인증 코드를 발송한 이메일 주소를 response 로 반환
5. 검증을 위해 클라이언트로부터 `이메일`과 `인증코드`를 받아 검증 진행 후, 일치하면 회원번호 반환
미리 구현해 놓은 이메일 인증 로직을 가져와 본인확인 후, 회원 번호를 발급할 수 있도록 구현하였습니다.
<br>
기능명을 '비밀번호 찾기' 로 해놓았지만,
코레일 서비스와 같이 본인 인증 후 비밀번호를 변경할 수 있는 페이지로 리다이렉트 할 수 있는 시나리오로 생각하고 로직을 구현하였습니다.
비밀 번호 찾기 로직 흐름은 다음과 같습니다.
1. 회원의 `이름`, `회원번호`를 요청으로 받음
2. DB 에 해당 정보를 가진 회원이 있는지 확인
3. 일치하는 회원이 있다면 회원 정보에 있는 이메일로 인증 코드를 보내고, 인증 코드를 발송한 이메일 주소를 response 로 반환
4. 검증을 위해 클라이언트로부터 이메일과 인증코드를 받아 검증 진행 후, 일치하면 성공메세지와 함께 임시 토큰을 발급 (비밀번호 변경 요청 엔드포인트 접근 시 필요. 유효시간 …
=> [FEATURE] 회원번호 찾기 및 비밀번호 찾기 로직 구현

k8s-argocd/argocd-application.yml, k8s-argocd/argocd-https.yml, k8s-argocd/argocd-ingress.yml
- close #100
- ArgoCD 적용 Application 스크립트 적용 - `argocd-application.yml`
- ArgoCD UI 를 외부에서 접속하기 위한 Ingress 스크립트 적용 `argocd-ingress.yml`
- https 로 접속하기 위한 Certificate 스크립트 적용 - `argocd-https.yml`
Github에 있는 소스코드를 기반으로 Kubernetes 인프라 환경을 동기화하기 위해 ArgoCD를 세팅하였습니다.
ArgoCD가 `/k8s` 폴더 하위 소스만을 추적하도록 세팅했습니다.
해당 설정으로 Github의 `/k8s` 하위 yml 소스들과 실제 클러스터가 sync가 안맞으면 ArgoCD가 github 기준으로 비교하여 강제로 sync를 맞춥니다.
로컬에서 아래와 같이 replicas를 임시로 늘려보는 테스트를 통해 Github 소스코드와 다른 경우 강제로 종료시키는 것을 확인했습니다.
해당 파일들은 모두 Local에서 적용하여 테스트 완료된 상태입니다.
argocd 관련 폴더인 `k8s-argocd` 하위 스크립트는 ArgoCD로 추적하고 있지 않으며, 단순 기록 및 보관을 위해 Github에 업로드하게 되었습니다.
ArgoCD UI는 아래 도메인으로 접속하여 확인할 수 있습니다. ID/PW는 Discord에 공유하겠습니다.
- https://argo.raillo.shop/
없음
=> [CHORE] ArgoCD 세팅

k8s/depl_svc.yml
- close #156
- limits.memory를 기존 500Mi → 1Gi로 상향 조정
- requests.memory도 250Mi → 512Mi로 변경하여 안정성 확보
원활한 성능 테스트를 위해 최대 메모리 limit을 상향 조정 하였습니다. 추가로 최소 memory request도 같이 상향 조정하였습니다.
현재는 노드 그룹에서 원하는 노드 크기, 최소 노드 크기를 0으로 변경하여 모든 Pod가 Pending으로 내려간 상태입니다.
따라서 백엔드 관련 도메인은 현재 접속하실 수 없으며 월요일에 다시 띄울 예정입니다.
없음
=> [CHORE] Spring Pod 최대 메모리 제한 1GiB로 상향 조정

src/main/java/com/sudo/railo/train/application/TrainService.java, src/main/java/com/sudo/railo/train/domain/Train.java, src/main/java/com/sudo/railo/train/domain/TrainCar.java, src/main/java/com/sudo/railo/train/domain/TrainSchedule.java, src/main/java/com/sudo/railo/train/infrastructure/TrainCarQueryRepositoryCustomImpl.java, src/main/java/com/sudo/railo/train/infrastructure/TrainRepository.java, src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepositoryCustomImpl.java
- close #172 
- Train - TrainCar `@OneToMany` 매핑 제거
- TrainCar - Seat `@OneToMany` 매핑 제거
- TrainSchedule - ScheduleStop `@OneToMany` 매핑 제거
- TrainSchedule `availableSeatsMap` 삭제
- 복잡한 테스트 데이터 설정 문제 해결과 테스트 용이성 확보를 위해 `@OneToMany`를 사용하지 않도록 수정했습니다.
- 사용하고 있지 않은 `availableSeatsMap` 필드를 삭제했습니다.
- `TrainScheduleTemplate`에 `@OneToMany`가 남아있는데, `ScheduleStop`을 반복적으로 생성하는 것보다 노선 테이블을 두는 게 좋을 것 같아서 이후 이슈에서 수정해보겠습니다.
없음
=> [REFACTOR] @OneToMany 제거

src/main/java/com/sudo/railo/global/config/RedisConfig.java
- close #178 
- RedisConfig에 objectMapper() 설정 추가
기존 Redis 관련 파일을 리팩토링하면서 LogoutToken 의 날짜 타입을 Duration 으로 변경 했었습니다.
그 이후 테스트 시 로그아웃 로직에서 다음과 같은 Redis 관련 직렬화/역직렬화 오류가 생긴 것을 확인하였습니다.
> org.springframework.data.redis.serializer.SerializationException: Could not write JSON: Java 8 date/time type java.time.Duration not supported by default
확인해본 결과 해당 문제는 Java 8 Date/Time API (예: java.time.Duration) 타입을 JSON으로 직렬화(또는 역직렬화)할 때 Jackson이 기본적으로 이를 지원하지 않아서 발생하는 오류로 확인되었습니다.
따라서 이를 해결하기 위해 Jackson 내부적으로 사용되고 있는 ObjectMapper 가 날짜/시간 API를 직렬화 및 역직렬화 할 수 있도록 JavaTImeModule()을 등록 후 GenericJacson2JsonRedisSerializer 에 주입시켜주었습니다.
```java
@Bean
public RedisTemplate<String, Object> customObjectRedisTemplate() {
RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>(); …
```
=> [BUG] 로그아웃 시 Redis Duration 타입 직렬화/역직렬화 오류

src/main/java/com/sudo/railo/auth/application/AuthService.java, src/main/java/com/sudo/railo/auth/application/dto/request/LoginRequest.java, src/main/java/com/sudo/railo/auth/application/dto/response/LoginResponse.java, src/main/java/com/sudo/railo/auth/docs/AuthControllerDocs.java, src/main/java/com/sudo/railo/auth/exception/TokenError.java, src/main/java/com/sudo/railo/auth/presentation/AuthController.java, src/main/java/com/sudo/railo/auth/security/jwt/JwtFilter.java, src/main/java/com/sudo/railo/auth/security/jwt/TokenProvider.java, src/main/java/com/sudo/railo/auth/success/AuthSuccess.java, src/main/java/com/sudo/railo/global/config/SecurityConfig.java, src/main/java/com/sudo/railo/global/exception/GlobalExceptionHandler.java
- close #168 
- 로그인 시 refreshToken은 `http only` 적용 및 `secure cookie`에 담아 프론트로 전달될 수 있게 수정
- body에 refreshToken은 제외하고 accessToken만 전달할 수 있도록 수정 
- 토큰 재발급 시 refreshToken을 `cookie`에서 가져올 수 있도록 변경
- 토큰 재발급은 accessToken의 유효시간이 만료되었을 경우 다시 발급받을 수 있는 로직이기 때문에 SecurityConfig 내 해당 엔드포인트를 `permitAll()`로 허용
- 따라서 로그인 된 사용자의 memberNo를 가져오는 것이 아니라 내부적으로 refreshToken에서 memberNo를 가져올 수 있도록 수정
- 메서드 이름 `memberNoLogin()` -> `login()` 으로 변경
- `TokenError` 파일 경로를 auth/exception 으로 변경
로그인에 성공하게 되면 body에는 accessToken 관련 정보만 담겨 프론트로 전달하게 됩니다.
refreshToken은 cookie에 담겨 따로 프론트로 보냅니다.
<br>
토큰 재발급을 테스트 하실 분들은 헤더에 Cookie 값으로 로그인 시 쿠키에 담아놓은 refreshToken 값을 직접 수동으로 넣어 테스트 해보실 수 있습니다 !
Hoppscotch로 테스트 후 문제 없음을 확인했습니다 👍
=> [REFACTOR] Http only 적용

src/main/java/com/sudo/railo/booking/domain/SeatReservation.java, src/main/java/com/sudo/railo/booking/domain/Ticket.java, src/main/java/com/sudo/railo/train/infrastructure/SeatRepositoryCustomImpl.java
- close #181 
- `SeatReservation` 유니크 제약조건 수정
- `Ticket` 엔티티의 `Seat` 연관관계 수정
- `SeatRepositoryCustomImpl` 쿼리 로직 수정
- 잘못된 조인 조건과 null check에 의해 구간 겹침이 제대로 판단되지 않았던것이 원인이었습니다.
- `Ticket` 엔티티의 `Seat` 연관관계 경우, 기존 `OneToOne` 관계였는데 같은 좌석에 대해 시간이 다른 경우가 발생할 수 있어서
해당 관계를 `ManyToOne`으로 변경하였습니다.
- `SeatRepositoryCustomImpl`, leftjoin 시 잘못된 join 조건을 수정하였고,
추가적으로 leftjoin 시 일부 필드가 null 값이 될 수 있기때문에 null check 하는 로직을 추가했습니다.
- 기존 스케줄 ID, 좌석 ID를 묶어 유니크 제약조건을 설정했는데, 겹치는 구간에 의해 동일한 경우가 발생할 수 있었습니다.
`reservation_id` 필드도 포함시켜 해결했습니다.
- 부산 -> 동대구, 동대구 -> 서울 예약 성공 확인했습니다.
- 부산 -> 동대구, 울산 -> 서울 예약 불가능 확인했습니다. (구간 1개역 겹치는 경우. 예약 불가능이 정상)
- 일단 되는것을 확인했습니다만, 다양한 경우로 테스트 부탁드립니다!
- (추가) 기존 스키마를 수정했기때문에 `ddl-auto: update`에 의해 자동으로 수정되지 않습니다.
`SeatReservation` 테이블과 `Ticket` 테이블을 편하신 방법을 통해 수동으로 날리고 테스트 부탁드립니다.
없음
=> [FIX] Booking 도메인 리팩토링 후 노선 중간 구간 예매 불가

src/main/java/com/sudo/railo/booking/application/ReservationService.java, src/main/java/com/sudo/railo/booking/application/SeatReservationService.java, src/main/java/com/sudo/railo/booking/domain/SeatReservation.java, src/main/java/com/sudo/railo/booking/infrastructure/SeatReservationRepository.java, src/main/java/com/sudo/railo/member/infrastructure/MemberRepositoryCustom.java
- close #186 
- ReservationService 리팩토링
- 겹치는 구간 중복 예약 문제 해결
- 동시성 문제 해결을 위한 비관적 락 도입
전체적으로 ReservationService를 리팩토링했습니다. 주요 변경 사항은 다음과 같습니다
- try-catch 문 대신 Unchecked Exception (RuntimeException)을 사용하여 예외 처리
- 메서드 분리를 통해 책임을 명확히 하고 가독성을 개선
- private 메서드의 순서를 재정렬하여 구조를 정리
기존 로직에서는 stationId를 기준으로 판별하기 때문에 구간 겹침 판단에 오류가 있었습니다. 따라서 stop_order 기반인 열차 스케줄의 정차역 순서로 구간 겹침을 판단하도록 로직을 수정했습니다. (참고 #188)
기존 낙관적 락 방식에서는 서로 다른 예약 엔티티가 동시에 생성되는 경우, 겹치는 구간에 대해 중복 예약이 허용되는 문제가 있었습니다. 
열차 좌석은 구조상 구간이 다를 경우 하나의 좌석에 여러 예약이 가능합니다.
예시: 
- A역 → C역 예약 (정차 순서: 1 → 3)
- B역 → D역 예약 (정차 순서: 2 → 4)
- 예약 트랜잭션 흐름: 예약(Reservation) 생성 → 예약_좌석(SeatReservation) 생성
- B-C 구간이 겹치므로 하나는 실패해야 하지만, 서로 다른 새로운 SeatReservation 엔티티가 동시에 생성되므로 `@Version`이 작동하지 않아 둘 다 성공하는 문제가 있었습니다.
따라서 비관적 락을 도입하여 아래와 같이 문제를 해결하였습니다.
1. 좌석별 예약 조회 …
=> [BUG] 좌석 충돌 예약 발생 오류

src/main/java/com/sudo/railo/booking/application/ReservationApplicationService.java, src/main/java/com/sudo/railo/payment/application/PaymentService.java, src/main/java/com/sudo/railo/payment/application/dto/projection/PaymentProjection.java, src/main/java/com/sudo/railo/payment/infrastructure/PaymentRepository.java, src/main/java/com/sudo/railo/payment/infrastructure/PaymentRepositoryCustom.java, src/main/java/com/sudo/railo/payment/infrastructure/PaymentRepositoryCustomImpl.java, src/main/java/com/sudo/railo/payment/presentation/PaymentController.java
- close #211
- PaymentController에 cancelPayment API 엔드포인트 추가 (POST /api/v1/payments/{paymentKey}/cancel)
- PaymentService에 결제 취소 및 자동 환불 처리 로직 구현
- 결제 취소 시 예약 상태도 함께 취소로 변경되도록 연동
- PaymentController에 getPaymentHistory API 엔드포인트 추가 (GET /api/v1/payments)
- PaymentService에 사용자별 결제 내역 조회 서비스 구현
- QueryDSL을 활용한 효율적인 데이터 조회 구조 도입
- PaymentProjection 클래스 구현 (필요한 필드만 조회하는 프로젝션)
- QueryDSL 기반 리포지토리 레이어 구현 (PaymentRepositoryCustom 인터페이스 및 PaymentRepositoryCustomImpl 구현체 추가)
1. 결제 취소 및 환불 처리 로직
결제 취소 시 즉시 환불 처리가 되도록 임시 구현되어 있습니다. 실제 운영에서는 PG사 API 연동이 필요하지만, 현재는 내부적으로 상태만 변경하는 방식으로 구현했습니다.
2. QueryDSL 도입으로 인한 성능 개선
결제 내역 조회 시 필요한 필드만 select하는 프로젝션을 사용하여 불필요한 데이터 로딩을 방지했습니다. 특히 연관 엔티티(Member, Reservation)의 모든 필드를 가져오지 않고 필요한 정보만 조회합니다.
3. 트랜잭션 처리
결제 취소: `@Transactional`로 원자성 보장
결제 내역 조회: …
=> [FEATURE] 결제 취소 기능 및 결제 내역 조회 기능 구현

src/test/java/com/sudo/railo/auth/application/AuthServiceTest.java, src/test/resources/application-test.yml
- close #218 
- `회원가입` 테스트 코드 작성
- 중복 이메일 회원가입 시도 예외 케이스 테스트 코드 작성
- `로그인` 테스트 코드 작성
- `로그아웃` 테스트 코드 작성
- 리프레시 토큰 유효시간 만료 시에도 로그아웃은 성공
- `토큰 재발급` 테스트 코드 작성
- 리프레시 토큰 정보 일치하지 않을 경우 예외 케이스 테스트 코드 작성
- `application-test.yml` 파일 수정
- jwt secret key 부분 길이 조정 
application-test.yml 파일에 임시로 설정해 둔 jwt secret key 길이가 짧아
토큰 부분 테스트 시 오류가 발생 하여 임시 key 의 길이를 더 길게 조정하였습니다 !
없음
=> [TEST] AuthService 테스트 코드 작성

build.gradle, src/main/java/com/sudo/railo/auth/security/jwt/TokenExtractor.java, src/test/java/com/sudo/railo/auth/security/jwt/TokenExtractorTest.java, src/test/java/com/sudo/railo/auth/security/jwt/TokenGeneratorTest.java, src/test/java/com/sudo/railo/auth/security/jwt/TokenValidatorTest.java
- close #208 
- TokenValidator 테스트 코드 작성
- TokenExtractor 테스트 코드 작성
- TokenGenerator 테스트 코드 작성 
해당 테스트로 Token 관련 클래스 테스트 커버리지 100% 달성하였습니다!
없음
=> [TEST] Token 기능 테스트

src/main/java/com/sudo/railo/member/infrastructure/MemberRepository.java, src/test/java/com/sudo/railo/member/application/MemberNoGeneratorTest.java, src/test/java/com/sudo/railo/member/application/MemberServiceTest.java
- close #205 
- MemberService 테스트 코드 작성
- `MemberRepository`에 soft delete 조건 우회하는 네이티브 쿼리 추가 
- MemberNoGenerator 테스트 코드 작성
없음
없음
=> [TEST] Member 서비스 테스트 코드 작성 

src/test/java/com/sudo/railo/booking/application/ReservationServiceTest.java, src/test/java/com/sudo/railo/booking/application/SeatReservationServiceTest.java, src/test/java/com/sudo/railo/booking/application/TicketServiceTest.java
- close #210 
- `ReservationService` 테스트 코드 작성
- `SeatReservationService` 테스트 코드 작성
- `TicketService` 테스트 코드 작성
- #231 
- #221 
> [!WARNING]
위 PR을 반영하여 작업한 브랜치 입니다.
GitHub 상 코드리뷰가 편하도록 작업한 커밋만 분리했습니다.
이 PR 단독으로 테스트가 불가능하며, 별도로 반영해 주셔야 테스트 가능합니다.
모두 머지 또는 해결된 후 리베이스하겠습니다!
`booking.application.dto.response`의 `TicketReadResponse`에서,
`Long seatReservationId`를 주석처리해주셔야 `TicketService` 테스트를 정상적으로 진행할 수 있습니다.
작성한 테스트 코드는 다음과 같습니다.
- 유효한 요청으로 예약이 성공한다
- 멤버번호와 예약 ID로 특정 예약 조회에 성공한다
- 올바른 멤버번호와 잘못된 예약 ID로 특정 예약 조회 시 예외를 반환한다
- 올바른 멤버번호와 만료된 예약 ID로 특정 예약 조회 시 예외를 반환한다
- 멤버번호로 관련한 예약 목록 조회에 성공한다
- 멤버번호로 만료된 예약을 포함한 예약 목록 조회에 성공한다
- 올바른 예약 삭제 요청 DTO로 예약 삭제에 성공한다
- 만료된 예약 일괄삭제에 성공한다
- 예약, 좌석, 승객 유형으로 좌석 예약 생성에 성공한다
- 좌석 예약 ID로 좌석 예약 삭제에 성공한다
- 예약 ID로 좌석 예약 삭제에 성공한다
- 예약, 좌석, 승객 유형으로 티켓 생성에 성공한다
- 멤버번호로 …
=> [TEST] Reservation 관련 서비스 테스트

src/main/java/com/sudo/railo/booking/application/ReservationApplicationService.java, src/main/java/com/sudo/railo/booking/application/ReservationService.java, src/main/java/com/sudo/railo/booking/application/SeatReservationService.java, src/main/java/com/sudo/railo/booking/infrastructure/SeatReservationRepository.java, src/main/java/com/sudo/railo/train/infrastructure/SeatRepository.java, src/test/java/com/sudo/railo/booking/application/ReservationApplicationServiceTest.java, src/test/java/com/sudo/railo/booking/application/ReservationConcurrentConflictTest.java
- close #207 
테스트를 진행하는 과정에서 로직 오류를 발견하여 아래와 같이 수정하였습니다.
유효하지 않은 좌석에 대한 검증 순서에 문제가 있어, 검증 로직의 흐름을 보다 명확하게 조정하였습니다.
record 내부의 List는 불변이 아니기 때문에 정렬 등 가공 시 원본이 변경될 수 있습니다. 데이터 무결성을 위해 new ArrayList<>()로 복사하여 사용하도록 수정했습니다.
기차 스케줄과 일치하지 않는 순서로 예매를 시도하는 경우 적절한 예외를 반환하도록 검증 로직을 추가하였습니다.
테스트 작성 중 동시성 이슈가 발생하여, 이를 해결하기 위해 다양한 락 처리 방식들을 공부하면서 적용하려고 하였습니다. 
다만, 트랜잭션이 분리되어 있고 좌석이 아닌 겹치는 구간을 기준으로 락을 걸어야 하는 구조적 특성상, 최적의 방법을 찾기 어려웠습니다.
일단 이중 락 방식으로 일단 동시성 문제를 해결하였고 k6로 400명 테스트에서 기존 코드와 비교하여 성능 차이는 크지 않음을 확인했습니다.
비관적 락이 두 번 발생하다 보니 성능에 영향을 줄 수 있는 여지가 있어, 추후 시간적 여유가 생기면 더 나은 구조와 방법으로 성능 개선을 진행할 예정입니다.
없음
=> [TEST] 예약 생성 기능 테스트

src/test/java/com/sudo/railo/payment/application/PaymentServiceTest.java, src/test/java/com/sudo/railo/support/fixture/PaymentFixture.java
- close #224
```
@BeforeEach 설정
├── Member 생성
│   ├── MemberFixture.createStandardMember()
│   └── memberRepository.save()
├── Train 생성
│   └── trainTestHelper.createKTX()
├── TrainSchedule 생성
│   └── trainScheduleTestHelper.createSchedule()
└── Reservation 생성
└── reservationTestHelper.createReservation()
```
```
├── processPaymentViaCard_success() ["카드 결제가 성공한다"]
│   ├── 카드 결제 요청
│   ├── 응답 데이터 검증
│   ├── Payment 엔티티 상태 확인
│   └── Reservation 상태 변경 확인
└── processPaymentViaBankAccount_success() ["계좌이체 결제가 성공한다"]
├── 계좌이체 결제 요청
├── 응답 데이터 검증
├── Payment 엔티티 상태 확인
└── Reservation 상태 변경 확인
```
```
├── processPayment_fail_whenAmountMismatch() ["금액이 일치하지 않으면 결제가 실패한다"]
│   ├── 잘못된 금액으로 결제 시도
│   └── PaymentError.PAYMENT_AMOUNT_MISMATCH 예외 검증
├── processPayment_fail_whenNotOwner() ["다른 사용자의 …
```
=> [TEST] 결제 관련 기능 테스트 코드 작성
